trigger:
  branches:
    include:
      - main   

pool:
  name: 'Default'

variables:
  appName: 'safari-zone'
  packageDir: 'dist'               # Vite build output folder

steps:
  # 1️⃣ Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '22'
    displayName: 'Install Node.js'

  # 2️⃣ Install Dependencies
  - script: |
      npm ci
      npm run build
    displayName: 'Install dependencies'

  # 4️⃣ Archive build folder into .zip
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      replaceExistingArchive: true
    displayName: 'Archive build output'

  - task: AzureRmWebAppDeployment@5
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Safari-Zone'
      appType: 'webAppLinux'
      WebAppName: 'safari-zone'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
      RuntimeStack: 'NODE|22-lts'
      DeploymentTypeLinux: 'oneDeploy'